spring:
  to: andre-bd@yandex.ru
  mail:
    host: smtp.yandex.ru
    username: "redis-test@yandex.ru"
    password: "RediS_test@733"
    port: 465
    protocol: smtps
    properties:
      mail.smtp:
        auth: true
        starttls.enable: true

  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "postgres"
    driver-class-name: "org.postgresql.Driver"

