spring:
  to: your_email
  mail:
    host: smtp.yandex.ru
    username: "send_email"
    password: "password"
    port: 465
    protocol: smtps
    properties:
      mail.smtp:
        auth: true
        starttls.enable: true

  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "postgres"
    driver-class-name: "org.postgresql.Driver"

