spring:
  to: your-email@yandex.ru
  mail:
    host: smtp.yandex.ru
    username: "sent-email@yandex.ru"
    password: "password"
    port: 465
    protocol: smtps
    properties:
      mail.smtp:
        auth: true
        starttls.enable: true

